export const Routes = [
  {
    id: 1,
    departure: "Accra",
    arrival: "Kumasi",
    type: "Scheduled",
    price: 350,
    schedule: "Saturday",
    time: "04:00",
    date: "thur 30th, may, 2024",
    arrivalTime: "03:28",
    terminal: "Circle Vip",
    seats: 45,
    ticket: "Buy Ticket",
  },
  {
    id: 2,
    departure: "Accra",
    arrival: "Takoradi",
    type: "Scheduled",
    price: 350,
    schedule: "Saturday",
    time: "04:00",
    date: "thur 30th, may, 2024",
    arrivalTime: "03:28",
    terminal: "Circle Vip",
    seats: 45,
    ticket: "Buy Ticket",
  },
  {
    id: 3,
    departure: "Accra",
    arrival: "Kumasi",
    type: "Scheduled",
    price: 350,
    schedule: "Saturday",
    time: "04:00",
    date: "thur 30th, may, 2024",
    arrivalTime: "03:28",
    terminal: "Circle Vip",
    seats: 45,
    ticket: "Buy Ticket",
  },
  {
    id: 4,
    departure: "Accra",
    arrival: "Kumasi",
    type: "Scheduled",
    price: 350,
    schedule: "Saturday",
    time: "04:00",
    date: "thur 30th, may, 2024",
    arrivalTime: "03:28",
    terminal: "Circle Vip",
    seats: 45,
    ticket: "Buy Ticket",
  },
  {
    id: 1,
    departure: "Accra",
    arrival: "Kumasi",
    type: "Scheduled",
    price: 350,
    schedule: "Saturday",
    time: "04:00",
    date: "thur 30th, may, 2024",
    arrivalTime: "03:28",
    terminal: "Circle Vip",
    seats: 45,
    ticket: "Buy Ticket",
  },
  {
    id: 1,
    departure: "Accra",
    arrival: "Kumasi",
    type: "Scheduled",
    price: 350,
    schedule: "Saturday",
    time: "04:00",
    date: "thur 30th, may, 2024",
    arrivalTime: "03:28",
    terminal: "Circle Vip",
    seats: 45,
    ticket: "Buy Ticket",
  },
  {
    id: 1,
    departure: "Accra",
    arrival: "Kumasi",
    type: "Scheduled",
    price: 350,
    schedule: "Saturday",
    time: "04:00",
    date: "thur 30th, may, 2024",
    arrivalTime: "03:28",
    terminal: "Circle Vip",
    seats: 45,
    ticket: "Buy Ticket",
  },
  {
    id: 1,
    departure: "Accra",
    arrival: "Kumasi",
    type: "Scheduled",
    price: 350,
    schedule: "Saturday",
    time: "04:00",
    date: "thur 30th, may, 2024",
    arrivalTime: "03:28",
    terminal: "Circle Vip",
    seats: 45,
    ticket: "Buy Ticket",
  },
  {
    id: 1,
    departure: "Accra",
    arrival: "Kumasi",
    type: "Scheduled",
    price: 350,
    schedule: "Saturday",
    time: "04:00",
    date: "thur 30th, may, 2024",
    arrivalTime: "03:28",
    terminal: "Circle Vip",
    seats: 45,
    ticket: "Buy Ticket",
  },
  {
    id: 1,
    departure: "Accra",
    arrival: "Kumasi",
    type: "Scheduled",
    price: 350,
    schedule: "Saturday",
    time: "04:00",
    date: "thur 30th, may, 2024",
    arrivalTime: "03:28",
    terminal: "Circle Vip",
    seats: 45,
    ticket: "Buy Ticket",
  },
  {
    id: 1,
    departure: "Accra",
    arrival: "Kumasi",
    type: "Scheduled",
    price: 350,
    schedule: "Saturday",
    time: "04:00",
    date: "thur 30th, may, 2024",
    arrivalTime: "03:28",
    terminal: "Circle Vip",
    seats: 45,
    ticket: "Buy Ticket",
  },
  {
    id: 1,
    departure: "Accra",
    arrival: "Kumasi",
    type: "Scheduled",
    price: 350,
    schedule: "Saturday",
    time: "04:00",
    date: "thur 30th, may, 2024",
    arrivalTime: "03:28",
    terminal: "Circle Vip",
    seats: 45,
    ticket: "Buy Ticket",
  },
  {
    id: 1,
    departure: "Accra",
    arrival: "Kumasi",
    type: "Scheduled",
    price: 350,
    schedule: "Saturday",
    time: "04:00",
    date: "thur 30th, may, 2024",
    arrivalTime: "03:28",
    terminal: "Circle Vip",
    seats: 45,
    ticket: "Buy Ticket",
  },
  {
    id: 1,
    departure: "Accra",
    arrival: "Kumasi",
    type: "Scheduled",
    price: 350,
    schedule: "Saturday",
    time: "04:00",
    date: "thur 30th, may, 2024",
    arrivalTime: "03:28",
    terminal: "Circle Vip",
    seats: 45,
    ticket: "Buy Ticket",
  },
  {
    id: 1,
    departure: "Accra",
    arrival: "Kumasi",
    type: "Scheduled",
    price: 350,
    schedule: "Saturday",
    time: "04:00",
    date: "thur 30th, may, 2024",
    arrivalTime: "03:28",
    terminal: "Circle Vip",
    seats: 45,
    ticket: "Buy Ticket",
  },
];
